### ISSUE TITLE
How to have Modal Auto Open on site load

### ISSUE THREAD

**Issue by coldes** [floriancapelle/jquery-flex-modal#8]
Can a Modal auto open on site load - ie Modal 5 "Alert"?

**Comment by floriancapelle** [comment]
Hi coldes, yes, you can do the following:
```
$(function() {
    $.flexModal.open('#YOUR_TARGET_ID');
});
```
Just make sure, the plugin is included before this code.
Please let me know if this works for you.

**Comment by coldes** [comment]
...nice one, many thanks
